blueprint:
  name: "QLVR-IT DDNS update"
  description: "Update IP-Adres ieder uur naar QLVR-IT DDNS"
  domain: automation
  input:
    inp_hostname:
      name: "DDNS Hostname, alleen de naam invullen ( sterretjes vervangen: ***.ha.qlvr-it.nl)"
      selector:
        text:
          suffix: ".ha.qlvr-it.nl"
    inp_username:
      name: "DDNS Username"
      selector:
        text:
    inp_password:
      name: "DDNS Password"
      selector:
        text:
          type: password
        
trigger:
  - platform: time_pattern
    hours: /1

action:
  - service: shell_command.qlvrit_ddns_update
    data:
      user: !input inp_username
      pass: !input inp_password
      hostname: !input inp_hostname